### ISSUE TITLE
user and password 

### ISSUE THREAD

**Issue by myoudjou** [TIBHannover/dspace-box#1]
hello 
merci pour la Virtual machine
juste une question :   
je veux savoirs le nom ainsi que le mot de passe concernant la vm 

merci

**Comment by mirjan-hoffmann** [comment]
Thank you for the interest in the dspace-box. I am switching to English and hope this is understandable for you.

The login information (user & password) can be found in https://github.com/TIBHannover/dspace-box/blob/master/ansible/group_vars/all.yml#L7-L8 => mail: test@test.edu, pw: admin
However, I have also included the information in the README now.

FYI: we expect to offer a more stable version of a dspace-box soon, which will then also be suitable for production installations.
